<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>bundleUUID</key>
  <string>72174d10-bb12-11e0-962b-112233445566</string>
  <key>name</key>
  <string>TestConsole</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>comment</key>
      <string>test pass</string>
      <key>match</key>
      <string>(^|\s)\d+ (tests|assertions|examples?|passed)</string>
      <key>name</key>
      <string>test.pass</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>test error</string>
      <key>match</key>
      <string>(\d+ errors)|(\d+\) Error:|Failing \w*:|cucumber(\s\S*)|\d failed)</string>
      <key>name</key>
      <string>test.error</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>test fail</string>
      <key>match</key>
      <string>(\d+ failures?)|(\d+\) Failure:)|\d+ undefined</string>
      <key>name</key>
      <string>test.fail</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>test cucumber</string>
      <key>match</key>
      <string>Feature|Scenario|Given|And|When|Then|\d+ skipped</string>
      <key>name</key>
      <string>test.cucumber</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>dots painting</string>
      <key>begin</key>
      <string>Started</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\.+|passed</string>
          <key>name</key>
          <string>test.pass</string>
        </dict>
        <dict>
          <key>match</key>
          <string>E+</string>
          <key>name</key>
          <string>test.error</string>
        </dict>
        <dict>
          <key>match</key>
          <string>F+</string>
          <key>name</key>
          <string>test.fail</string>
        </dict>
      </array>
      <key>end</key>
      <string>Finished</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>color syntax response</string>
      <key>match</key>
      <string>Syntax OK</string>
      <key>name</key>
      <string>test.pass</string>
    </dict>
  </array>
  <key>scopeName</key>
  <string>tests.ruby</string>
  <key>uuid</key>
  <string>72174d10-bb12-11e0-962b-112233445566</string>
</dict>
</plist>
